import { prisma } from "./config/database.js";

const PATIENTS = [
  {
    uhid: "UHID-2026-00001-2863",
    registrationType: "New Registration",
    title: "Mr.",
    firstName: "Utkarsh",
    middleName: "",
    lastName: "Ladla",
    fullName: "Utkarsh Ladla",
    gender: "Male",
    maritalStatus: "Single",
    dob: new Date("2005-08-12"),
    age: 21,
    guardianName: "Sanjay Ladla",
    guardianRelation: "Father",
    regDate: new Date(),
    mobile: "4354353453",
    address: "B-12, Sector 62, Institutional Area",
    country: "India",
    state: "Delhi",
    districtCity: "New Delhi",
    pinCode: "110092",
    email: "utkarsh.ladla@gmail.com",
    emergencyName: "Sanjay Ladla",
    emergencyRelationship: "Father",
    emergencyContact: "9876543210",
    nationality: "Indian",
    aadhaarCard: "435435345312",
    panNo: "BKMPE3518B",
    payerType: "direct",
    payer: "CASH / CASH",
    provider: "General Medicine",
    referredBy: "Self / Direct",
    status: "Active",
    remarks: "Patient presented with fever and mild abdominal discomfort.",
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80",
  },
  {
    uhid: "UHID-2026-00002-3183",
    registrationType: "New Registration",
    title: "Dr.",
    firstName: "Sameer",
    middleName: "",
    lastName: "Sen",
    fullName: "Dr. Sameer Sen",
    gender: "Male",
    maritalStatus: "Married",
    dob: new Date("1992-03-15"),
    age: 34,
    guardianName: "Pooja Sen",
    guardianRelation: "Spouse",
    regDate: new Date(),
    mobile: "8899889988",
    address: "Room 102, Green Park Main",
    country: "India",
    state: "Delhi",
    districtCity: "New Delhi",
    pinCode: "110016",
    email: "dr.sameer@hospital.org",
    emergencyName: "Pooja Sen",
    emergencyRelationship: "Spouse",
    emergencyContact: "8899889988",
    nationality: "Indian",
    aadhaarCard: "889988998812",
    panNo: "BKMPL3213B",
    payerType: "insurance",
    payer: "Star Health Insurance",
    sponsor: "Star Health TPA",
    provider: "Surgical Care",
    referredBy: "Dr. Sameer Sen 3105",
    status: "Active",
    remarks: "Post-consultation surgical admission requested.",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
  },
  {
    uhid: "UHID-2026-00003-4921",
    registrationType: "New Registration",
    title: "Mr.",
    firstName: "Rajesh",
    middleName: "",
    lastName: "Sharma",
    fullName: "Rajesh Sharma",
    gender: "Male",
    maritalStatus: "Married",
    dob: new Date("1981-04-18"),
    age: 45,
    guardianName: "Pooja Sharma",
    guardianRelation: "Spouse",
    regDate: new Date(),
    mobile: "9811223344",
    address: "Flat 402, Block B, Preet Vihar",
    country: "India",
    state: "Delhi",
    districtCity: "New Delhi",
    pinCode: "110092",
    email: "rajesh.sharma@yahoo.com",
    emergencyName: "Pooja Sharma",
    emergencyRelationship: "Spouse",
    emergencyContact: "9811223344",
    nationality: "Indian",
    aadhaarCard: "981122334455",
    panNo: "AABCS1234D",
    payerType: "insurance",
    payer: "HDFC ERGO",
    sponsor: "HDFC ERGO Corporate",
    provider: "Internal Medicine",
    referredBy: "Dr. Abhishek Bansal 2273",
    status: "Active",
    remarks: "Chronic hypertension monitoring and medication titration.",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
  },
  {
    uhid: "UHID-2026-00004-5812",
    registrationType: "New Registration",
    title: "Mrs.",
    firstName: "Sunita",
    middleName: "",
    lastName: "Verma",
    fullName: "Sunita Verma",
    gender: "Female",
    maritalStatus: "Married",
    dob: new Date("1988-11-22"),
    age: 38,
    guardianName: "Ramesh Verma",
    guardianRelation: "Spouse",
    regDate: new Date(),
    mobile: "9871122334",
    address: "Sector 15, Vasundhara",
    country: "India",
    state: "Uttar Pradesh",
    districtCity: "Ghaziabad",
    pinCode: "201012",
    email: "sunita.verma@outlook.com",
    emergencyName: "Ramesh Verma",
    emergencyRelationship: "Spouse",
    emergencyContact: "9871122334",
    nationality: "Indian",
    aadhaarCard: "987112233490",
    panNo: "BVMPV4432K",
    payerType: "direct",
    payer: "CASH / CASH",
    provider: "Pediatrics & Gynecology",
    referredBy: "Dr. Sania Mirza 2231",
    status: "Active",
    remarks: "Elective observation and routine labs requested.",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
  },
  {
    uhid: "UHID-2026-00005-7210",
    registrationType: "New Registration",
    title: "Mr.",
    firstName: "Amitabh",
    middleName: "",
    lastName: "Mehra",
    fullName: "Amitabh Mehra",
    gender: "Male",
    maritalStatus: "Married",
    dob: new Date("1974-06-05"),
    age: 52,
    guardianName: "Kavita Mehra",
    guardianRelation: "Spouse",
    regDate: new Date(),
    mobile: "9988776655",
    address: "C-45, South Extension Part 2",
    country: "India",
    state: "Delhi",
    districtCity: "New Delhi",
    pinCode: "110049",
    email: "amitabh.mehra@gmail.com",
    emergencyName: "Kavita Mehra",
    emergencyRelationship: "Spouse",
    emergencyContact: "9988776655",
    nationality: "Indian",
    aadhaarCard: "998877665521",
    panNo: "BPMPS8876L",
    payerType: "insurance",
    payer: "Max Bupa",
    sponsor: "Max Bupa Health",
    provider: "Cardiology",
    referredBy: "Dr. Abhishek Bansal 2273",
    status: "Active",
    remarks: "Post-op observation and cardiology monitoring.",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
  },
];

async function seed() {
  console.log("Seeding patient records with photos and full attributes...");
  for (const p of PATIENTS) {
    await prisma.patient.upsert({
      where: { uhid: p.uhid },
      update: {
        fullName: p.fullName,
        photoUrl: p.photoUrl,
        mobile: p.mobile,
        email: p.email,
        address: p.address,
        state: p.state,
        districtCity: p.districtCity,
        pinCode: p.pinCode,
        payerType: p.payerType,
        payer: p.payer,
        sponsor: p.sponsor,
        guardianName: p.guardianName,
        guardianRelation: p.guardianRelation,
        emergencyName: p.emergencyName,
        emergencyContact: p.emergencyContact,
        emergencyRelationship: p.emergencyRelationship,
        aadhaarCard: p.aadhaarCard,
        panNo: p.panNo,
        dob: p.dob,
        age: p.age,
        remarks: p.remarks,
        referredBy: p.referredBy,
      },
      create: p,
    });
  }
  console.log("Patients seeded successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Error seeding patients:", err);
  process.exit(1);
});
